blog1/urls.py
from django.urls import path
app_name='blog1'

urlpatterns=[

]

mysite/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog1/', include('blog1.urls')),
    path('shop/', include('shop.urls'))
]

urlpatterns +=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns +=[
        path('__debug__/', include(debug_toolbar.urls))
    ]

shop/urls.py
from django.urls import path, register_converter
from .converters import FourDigitYearConverter
from .import views
register_converter(FourDigitYearConverter,'yyyy')
app_name = "shop"
urlpatterns =[
    path('archives/<yyyy:year>/', views.archives_year, name="archives_year"),
    path('',views.item_list, name='item_list'),
    path('<int:pk>/',views.item_detail, name='item_detail'),
    path('new/', views.item_new, name='item_new'),
    path('<int:pk>/edit/',views.item_edit, name='item_edit'),
]

blog1/models.py
from django.db import models
from django.conf import settings
from mysite.utils import uuid_upload_to

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    photo = models.ImageField(blank=True, upload_to=uuid_upload_to)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class Comment (models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    message = models.TextField()

common/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from mysite.utils import uuid_upload_to
from django.urls import reverse
# Create your models here.

class Item(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField(blank=True)
    price = models.PositiveIntegerField()
    photo = models.ImageField(blank=True, upload_to=uuid_upload_to)
    is_publish = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)#추가될 때에 자동 저장
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '<{}> {}'.format(self.pk, self.name)

    def get_absolute_url(self):
        return reverse('shop:item_detail', args=[self.pk])

shop/templates/forms.py
from django import forms
from . models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'

common/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
import logging
import re
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from . models import Item
from . forms import ItemForm
# Create your views here.
def archives_year(request,year):
    return HttpResponse('{}년도에 대한 내용'.format(year))

def item_list(request):
    qs= Item.objects.all()
    q=request.GET.get('q','')
    if q:
        qs = qs.filter(name__icontains=q)

    logger.debug('query : {}'.format(q))

    return render(request, 'shop/item_list.html',{
        'item_list':qs,
        'q' : q,
    })

def item_detail(request,pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'shop/item_list.html',{
        'item': item,
    })

def item_new(request, item=None):
    if request.method == 'POST':
        form = ItemForm(request.POST,request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect(item)
    else:
        form=ItemForm(instance=item)

    return render(request, 'shop/item_form.html', {
        "form": form,
    })


def item_edit(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return item_new(request, item)

blog1/templates/blog1/layout.html
{%  extends "layout.html" %}

{% block title %}Blog by askCompany{% endblock %}

{% block extra_head%}
    {{ block.super }}
    <link rel="stylesheet" href=""{% static "blog1/blog1.css" %}" />
    <style>

    </style>
{% endblock %}

{% block extra_body %}
    {{ block.super }}
{% endblock %}

mysite/templates/mysite/layout.html
{% load static fresh_static%}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>장고 개빡치네</title>
    <style>
        body{background-color: #5b80b2;}
    </style>
    <link rel="stylesheet" href="{% fresh_static"main.css" %}"/>
</head>
<body>
    <h1>Ask Company</h1>

    {% block content %}
        <script src="{% static "main.js"%}"></script>
    {% endblock %}


</body>
</html>

shop/templates/shop/item_detail.html
{% extends "shop/layout.html" %}
{% block content %}
{% load humanize %}


        <h2>{{ item.name }}</h2>

         가격:{{ item.price|intcomma }}원
         {% if item.desc %}
             <p>
             {{ item.desc}}
             </p>
         {% endif %}

        <hr/>
        <a href="/shop/">목록</a>

{% endblock %}

shop/templates/shop/item_form.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
    </head>
    <body>
        <div class="container">
            <div class="col-sm-12">
                <h2>New Item</h2>

                {% if initial %}
                    <div class="alert alert-info">
                        initial: {{ initial }}
                    </div>
                {% endif %}
                <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                    {% csrf_token %}
                    <table class = "table table-bordered">
                    {{ form.as_table }}
                    </table>
                    <input type="submit" value="저장하기" class="btn btn-primary" />
                </form>
            </div>
        </div>
    </body>
</html>

shop/templates/shop/item_list.html
{% extends "shop/layout.html" %}
{% block content %}
    <form action="" method="GET">
        <input type="text" name="q" value="{{ q }}"/>
        <input type="submit" value="search"/>
    </form>

    <ul>
        {%  for item in item_list %}
            <li>
                <a href="{{ item.get_absolute_url }}">
                {{ item.name }}
                </a>
                {{ item.price }}
                {{ item.desc }}
            </li>
        {% endfor %}
    </ul>

    <hr/>
    <a href=""{% url "shop:item_list" %}>목록</a>
    <a href=""{% url "shop:item_edit" item.pk %}>수정</a>
{% endblock %}

shop/templates/shop/layout.html
{% load static %}
{%  extends "layout.html" %}

{% block title %}shop by askcomapny
{% endblock %}

{% block extra_head%}
    {{ block.super }}
    <link rel="stylesheet" href=""{% static "shop/shop.css" %}" />
{% endblock %}

{% block extra_body %}
    {{ block.super }}
{% endblock %}